; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -mattr=+m,+xcvmac -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=RV32XCVMAC
; RUN: llc -mtriple=riscv32 -mattr=+m -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=RV32M
; RUN: llc -mtriple=riscv64 -mattr=+m,+xcvmac -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=RV64XCVMAC

define i32 @mac_add_mul(i32 %acc, i32 %lhs, i32 %rhs) {
; RV32XCVMAC-LABEL: mac_add_mul:
; RV32XCVMAC:       # %bb.0:
; RV32XCVMAC-NEXT:    cv.mac a0, a1, a2
; RV32XCVMAC-NEXT:    ret
;
; RV32M-LABEL: mac_add_mul:
; RV32M:       # %bb.0:
; RV32M-NEXT:    mul a1, a1, a2
; RV32M-NEXT:    add a0, a0, a1
; RV32M-NEXT:    ret
;
; RV64XCVMAC-LABEL: mac_add_mul:
; RV64XCVMAC:       # %bb.0:
; RV64XCVMAC-NEXT:    mul a1, a1, a2
; RV64XCVMAC-NEXT:    addw a0, a0, a1
; RV64XCVMAC-NEXT:    ret
  %mul = mul i32 %lhs, %rhs
  %res = add i32 %acc, %mul
  ret i32 %res
}

define i32 @mac_add_mul_commuted(i32 %acc, i32 %lhs, i32 %rhs) {
; RV32XCVMAC-LABEL: mac_add_mul_commuted:
; RV32XCVMAC:       # %bb.0:
; RV32XCVMAC-NEXT:    cv.mac a0, a1, a2
; RV32XCVMAC-NEXT:    ret
;
; RV32M-LABEL: mac_add_mul_commuted:
; RV32M:       # %bb.0:
; RV32M-NEXT:    mul a1, a1, a2
; RV32M-NEXT:    add a0, a1, a0
; RV32M-NEXT:    ret
;
; RV64XCVMAC-LABEL: mac_add_mul_commuted:
; RV64XCVMAC:       # %bb.0:
; RV64XCVMAC-NEXT:    mul a1, a1, a2
; RV64XCVMAC-NEXT:    addw a0, a1, a0
; RV64XCVMAC-NEXT:    ret
  %mul = mul i32 %lhs, %rhs
  %res = add i32 %mul, %acc
  ret i32 %res
}

define i32 @msu_sub_mul(i32 %acc, i32 %lhs, i32 %rhs) {
; RV32XCVMAC-LABEL: msu_sub_mul:
; RV32XCVMAC:       # %bb.0:
; RV32XCVMAC-NEXT:    cv.msu a0, a1, a2
; RV32XCVMAC-NEXT:    ret
;
; RV32M-LABEL: msu_sub_mul:
; RV32M:       # %bb.0:
; RV32M-NEXT:    mul a1, a1, a2
; RV32M-NEXT:    sub a0, a0, a1
; RV32M-NEXT:    ret
;
; RV64XCVMAC-LABEL: msu_sub_mul:
; RV64XCVMAC:       # %bb.0:
; RV64XCVMAC-NEXT:    mul a1, a1, a2
; RV64XCVMAC-NEXT:    subw a0, a0, a1
; RV64XCVMAC-NEXT:    ret
  %mul = mul i32 %lhs, %rhs
  %res = sub i32 %acc, %mul
  ret i32 %res
}

define i32 @no_msu_sub_mul_acc(i32 %acc, i32 %lhs, i32 %rhs) {
; RV32XCVMAC-LABEL: no_msu_sub_mul_acc:
; RV32XCVMAC:       # %bb.0:
; RV32XCVMAC-NEXT:    mul a1, a1, a2
; RV32XCVMAC-NEXT:    sub a0, a1, a0
; RV32XCVMAC-NEXT:    ret
;
; RV32M-LABEL: no_msu_sub_mul_acc:
; RV32M:       # %bb.0:
; RV32M-NEXT:    mul a1, a1, a2
; RV32M-NEXT:    sub a0, a1, a0
; RV32M-NEXT:    ret
;
; RV64XCVMAC-LABEL: no_msu_sub_mul_acc:
; RV64XCVMAC:       # %bb.0:
; RV64XCVMAC-NEXT:    mul a1, a1, a2
; RV64XCVMAC-NEXT:    subw a0, a1, a0
; RV64XCVMAC-NEXT:    ret
  %mul = mul i32 %lhs, %rhs
  %res = sub i32 %mul, %acc
  ret i32 %res
}

define i32 @no_mac_multi_use_mul(i32 %acc, i32 %lhs, i32 %rhs, ptr %dst) {
; RV32XCVMAC-LABEL: no_mac_multi_use_mul:
; RV32XCVMAC:       # %bb.0:
; RV32XCVMAC-NEXT:    mul a1, a1, a2
; RV32XCVMAC-NEXT:    add a0, a0, a1
; RV32XCVMAC-NEXT:    sw a1, 0(a3)
; RV32XCVMAC-NEXT:    ret
;
; RV32M-LABEL: no_mac_multi_use_mul:
; RV32M:       # %bb.0:
; RV32M-NEXT:    mul a1, a1, a2
; RV32M-NEXT:    add a0, a0, a1
; RV32M-NEXT:    sw a1, 0(a3)
; RV32M-NEXT:    ret
;
; RV64XCVMAC-LABEL: no_mac_multi_use_mul:
; RV64XCVMAC:       # %bb.0:
; RV64XCVMAC-NEXT:    mul a1, a1, a2
; RV64XCVMAC-NEXT:    addw a0, a0, a1
; RV64XCVMAC-NEXT:    sw a1, 0(a3)
; RV64XCVMAC-NEXT:    ret
  %mul = mul i32 %lhs, %rhs
  store i32 %mul, ptr %dst
  %res = add i32 %acc, %mul
  ret i32 %res
}
